// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 36
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){


var __e;(function(){(function(a){__e=a;__e.a="e";__e.b=["google"];__e.c=!0})(function(){return va})})();



var __ua;(function(){var a;(function(a){__ua=a;__ua.a="ua";__ua.b=["google"];__ua.c=!0})(function(b){var c={},d={},e={},f={},g={};if(b[""]){var h=b[""];Da(S(h["21"],"fieldName","value"),d);Da(S(h[""],"index","group"),e);Da(S(h["12"],"index","dimension"),f);Da(S(h[""],"index","metric"),g);b[""]=null;h["21"]=void 0;h[""]=
void 0;h["12"]=void 0;h[""]=void 0;var k=Ea(h,void 0);b=Ea(b,k)}Da(S(b["21"],"fieldName","value"),d);Da(S(b[""],"index","group"),e);Da(S(b["12"],"index","dimension"),f);Da(S(b[""],"index","metric"),g);var l=Fa(b[""]),m="",n="";b["24"]&&"string"==typeof b[""]?""!==b[""]&&(n=b[""],
m=n+"."):(n=Ga(),m=n+".");var p={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0},t={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,
storeGac:!0},r=function(a){var b=[].slice.call(arguments,0);b[0]=m+b[0];l.apply(window,b)},v=function(a,b){return void 0===b?b:a(b)},y=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&r("set",a+c,b[c])},H=function(){},G=function(a,b,c){var d=0;if(a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&p[e]||!c&&void 0===p[e])){var f=t[e]?Ja(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d},D={name:n};G(d,D,!0);l("create",b["27"]||c.trackingId,D);r("set","&gtm",ra(!0));(function(a,c){void 0!==b[c]&&r("set",a,b[c])})("nonInteraction","22");y("contentGroup",
e);y("dimension",f);y("metric",g);var K={};G(d,K,!1)&&r("set",K);var C;b["16"]&&r("require","linkid","linkid.js");r("set","hitCallback",function(){var a=d&&d.hitCallback;T(a)&&a();b["30"]()});if("TRACK_EVENT"==b["25"]){
b["14"]&&(r("require","ec","ec.js"),H());var E={hitType:"event",eventCategory:String(b["20"]||c.category),eventAction:String(b["19"]||c.action),eventLabel:v(String,b[""]||c.label),eventValue:v(Ka,b[""]||c.value)};G(C,E,!1);r("send",E);}else if("TRACK_SOCIAL"==b["25"]){}else if("TRACK_TRANSACTION"==b["25"]){}else if("TRACK_TIMING"==b["25"]){}else if("DECORATE_LINK"==b["25"]){}else if("DECORATE_FORM"==b["25"]){}else if("TRACK_DATA"==b["25"]){}else{b["14"]&&(r("require","ec","ec.js"),H());if(b["13"]||"DISPLAY_FEATURES"==
b[""]){var R="_dc_gtm_"+String(b["27"]).replace(/[^A-Za-z0-9-]/g,"");r("require","displayfeatures",void 0,{cookieName:R})}"DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==b[""]&&(R="_dc_gtm_"+String(b["27"]).replace(/[^A-Za-z0-9-]/g,""),r("require","adfeatures",{cookieName:R}));C?r("send","pageview",C):r("send","pageview");}if(!a){var M=b["28"]?"u/analytics_debug.js":"analytics.js";b[""]&&!b["28"]&&(M="internal/"+M);a=!0;Oa(x("https:","http:","//www.google-analytics.com/"+M,d&&d.forceSSL),function(){var a=Ma();a&&a.loaded||
b["31"]();},b["31"])}})})();










var Gb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Hb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ib=function(a){if(null==a)return String(a);var b=Hb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Jb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ha=function(a){if(!a||"object"!=Ib(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Jb(a,"constructor")&&!Jb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Jb(a,b)},Ea=function(a,b){var c=b||("array"==Ib(a)?[]:{}),d;for(d in a)if(Jb(a,d)){var e=a[d];"array"==Ib(e)?("array"!=Ib(c[d])&&(c[d]=[]),c[d]=Ea(e,c[d])):Ha(e)?(Ha(c[d])||(c[d]={}),c[d]=Ea(e,c[d])):c[d]=e}return c};var Ca={},mb=null,Kb=Math.random();Ca.f="GTM-NZHN7H";var Lb=null,va=null,Ua=!1,Mb="//www.googletagmanager.com/a?id="+Ca.f+"&cv=36",Nb={},Ob={},Va={};var Ya,Za,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,
Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf;
(function(){var a=function(a){return{toString:function(){return a}}};Pb=a("");Qb=a("");Rb="";Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("0");ac=a("1");bc=a("");cc=a("");dc=a("");
ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");
sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("2");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");
Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");
$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");od=a("");
pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ya=a("3");Ad=a("");Bd=a("30");Cd=a("31");Dd=a("");Ed=a("");
Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Za=a("4");Ld=a("");Md=a("");Nd=a("5");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");
Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("6");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("8");ne=a("");oe=a("");pe=a("");qe=a("");
re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");
Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("9");Ze=
a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");pf=a("");
qf=a("");rf=a("");sf=a("");tf=a("");uf=a("");vf="";wf=a("");xf=a("");yf=a("");zf=a("");Af=a("");Bf=a("");Cf=a("");Df=a("");Ef=a("");Ff=a("");Gf=a("");Hf=
a("");If=a("");Jf=a("");Kf=a("");Lf=a("")})();var Fb=function(a,b){Ea(a,b)},wb=function(){},T=function(a){return"function"==typeof a},$a=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Mf=function(a){return"number"==Ib(a)&&!isNaN(a)},Nf=function(a){return/^[0-9]+$/.test(a)},jb=function(a){return"string"==Ib(a)},Of=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Pf=function(a,b){if(a&&$a(a)&&0!=a.length)for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},ua=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},X=function(a){return Math.round(Number(a))||0},Ja=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Qf=function(a){var b=[];if($a(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},L=function(){return new Date},Ba=function(a,b){if(!Mf(a)||!Mf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Rf=function(){this.prefix="gtm.";this.values={}};
Rf.prototype.set=function(a,b){this.values[this.prefix+a]=b};Rf.prototype.get=function(a){return this.values[this.prefix+a]};Rf.prototype.contains=function(a){return void 0!==this.get(a)};
var Sf=function(a,b,c){try{if(!a[$d])return a[Ya](a,b||wb,c||wb);c&&c()}catch(d){}return!1},Tf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ua(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Uf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Vf=function(a){var b=Ca.f;return function(){return a(b)}},Wf=function(a){for(var b=0;b<a.length;b++)a[b]()},Ga=function(){return"gtm"+Xf()},
Xf=function(){var a=mb.sequence||0;mb.sequence=a+1;return a},Ia=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Yf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Zf=function(a,b){0==b?a.fc=!0:a.la=!0;var c=a.i;a.G&&(a.G.xb[c]=b);Nb[c]&&(Nb[c].state=b)},$f=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},ag=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var z=window,P=document,cg=navigator,Ta=function(a,b){var c=z[a];z[a]=void 0===c?b:c;return z[a]},ka=function(a,b,c,d){return(d||"http:"!=z.location.protocol?a:b)+c},dg=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},qb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;qb(d,b);c&&(d.onerror=c);dg(d);return d},Wa=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";dg(c);qb(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},Q=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},oa=function(a,b,c,d){a.removeEventListener?
a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){z.setTimeout(a,0)},sb=!1,tb=[],eg=function(a){if(!sb){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){sb=!0;for(var e=0;e<tb.length;e++)w(tb[e])}tb.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},fg=0,gg=function(){if(!sb&&140>fg){fg++;try{P.documentElement.doScroll("left"),eg()}catch(a){z.setTimeout(gg,
50)}}},ha=function(a){var b=P.getElementById(a);if(b&&sa(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(sa(document.all[a][c],"id")==a)return document.all[a][c];return b},sa=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},hg=function(a){return a.target||a.srcElement||{}},ta=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},zb=function(a){var b=
P.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},ig=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;var f=a;for(e=0;f&&e<=c;e++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},ng=!1,og=[],pg=function(){if(!ng){ng=!0;for(var a=0;a<og.length;a++)w(og[a])}},qg=function(a){a=a||z;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},xb=function(a){window.console&&
window.console.log&&window.console.log(a)};var rg=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},W=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||z.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||z.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:z.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Of(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=rg(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},wa=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},V=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var pa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var kb=function(a){return encodeURIComponent(a)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=W(V(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var S=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},ob=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},Da=function(a,b){Ea(a,b)},Ka=function(a){return X(a)},Ab=function(a,b){return Of(a,b)};var sg={event:function(a){var b=a[1];if(jb(b)&&!(3<a.length)){var c;if(2<a.length){if(!Ha(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=Ea(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&Ha(a[1])?b=Ea(a[1],void 0):3==a.length&&jb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var tg=new Rf,ug={},wg={set:function(a,b){Ea(vg(a,b),ug)},get:function(a){return Z(a,2)},reset:function(){tg=new Rf;ug={}}},Z=function(a,b){var c;if(2!=b)c=tg.get(a);else a:{for(var d=a.split("."),e=0,f=ug.eventModel;void 0!==f&&e<d.length;e++)f=f[d[e]];if(void 0!==f||1<e)c=f;else{var g=ug;for(e=0;e<d.length;e++){if(void 0===g[d[e]]){c=void 0;break a}g=g[d[e]]}c=g}}return c},xg=function(a,b){tg.set(a,b);Ea(vg(a,b),ug)},vg=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]=
{};d[e[e.length-1]]=b;return c};var yg=!1,zg=!1;var Fa=function(a){var b=z;b.GoogleAnalyticsObject||(b.GoogleAnalyticsObject=a||"ga");var c=b.GoogleAnalyticsObject;if(!b[c]){var d=function(){d.q=d.q||[];d.q.push(arguments)};d.l=Number(L());b[c]=d}return b[c]},Ma=function(){var a=z;return a.GoogleAnalyticsObject&&a[a.GoogleAnalyticsObject]},Na=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Ma();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};var Ag=Math.random(),Bg="0.050000">Ag;
var Cg=function(a,b){if(Bg){var c=Mb,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",L().getTime()-X(Lb));c+="&sr=0.050000";d("&ps=",Ag);d("&cb=",Ba());F(c)}},Dg=wb,Eg=function(){var a=!1;
};var Gg=function(a){var b=mb.zones;return b?b.checkState(Ca.f,a):Fg},Fg={active:!0,isWhitelisted:function(){return!0}};var Ig=wb,Jg=[],Kg=!1,Lg=function(a){return z["dataLayer"].push(a)},Mg=function(a){var b=!1;return function(){!b&&T(a)&&w(Vf(a));b=!0}},Vg=function(){for(var a=!1;!Kg&&0<Jg.length;){Kg=!0;delete ug.eventModel;var b=Jg.shift();if(T(b))try{b.call(wg)}catch(La){}else if($a(b))a:{var c=b;if(jb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=ug,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(La){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&jb(l[0])){var m=sg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Kg=!1;continue}}var n=void 0,p=void 0,t=b,r=t._clear;for(p in t)t.hasOwnProperty(p)&&"_clear"!==p&&(r&&xg(p,void 0),xg(p,t[p]));var v=!1,y=t.event;if(y){t.hasOwnProperty("gtm.uniqueEventId")||(t["gtm.uniqueEventId"]=Xf(),xg("gtm.uniqueEventId",t["gtm.uniqueEventId"]));n=t["gtm.uniqueEventId"];va=y;var H=Gg(n);if(H.active){var G=Mg(t.eventCallback),D=t.eventTimeout;
D&&z.setTimeout(G,Number(D));v=Ig(n,y,H.isWhitelisted,G,t.eventReporter)}}Lb||(Lb=t["gtm.start"])&&Dg();var K,C=t,E=n,A=y,B=ug;va=null;a=v||a}Kg=!1}return!a},Wg=function(){var a=Vg();try{var b=z["dataLayer"].hide;if(b&&void 0!==b[Ca.f]&&b.end){b[Ca.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Xg=function(){var a=Ta("dataLayer",[]),b=Ta("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};tb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});og.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Jg.push.apply(Jg,b);300<this.length;)this.shift();return Vg()};Jg.push.apply(Jg,a.slice(0));w(Wg)};var Yg,Zg,$g;
var ah=/(Firefox\D28\D)/g.test(cg.userAgent),bh={},hh=function(a,b){return function(c){c=c||z.event;var d=hg(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=ig(d,["a","area"]),e=!d||!d.href||ch(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?$g:Zg;if(c.defaultPrevented||!1===c.returnValue||c.eb&&c.eb()){if(d){var g={simulateDefault:!1},h=dh(f,["wnc","nwnc"]);h&&eh(a,d,g,f.wt,h)}}else{if(d){g={};var k,l=dh(f,["wnc",
"nwnc","nwc","wc"]);(k=eh(a,d,g,f.wt,l))||(fh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ah;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=gh(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},eh=function(a,b,c,d,e){var f=d||2E3,g=xa(b,a);switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g.eventTimeout=f;g.eventCallback=ih(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=
e||"";g.event="gtm.formSubmit";g.eventTimeout=f;g.eventCallback=jh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";break;default:return!0}return Lg(g)},kh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},gh=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(cg.userAgent),e=kh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);
b.targetWindow=z.frames&&z.frames[f]||z[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+L().getTime(),b.targetWindow=z.open("",b.targetWindowName));break;default:d&&!z.frames[e]?(b.simulateDefault=!1,c=!0):(z.frames[e]||(b.targetWindowName=e),b.targetWindow=z.frames[e]||z.open("",e))}return c},ih=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||L().getTime(),500>L().getTime()-c&&z.setTimeout(ih(a,
b,c),25)))}},jh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;lh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||L().getTime(),500>L().getTime()-c&&z.setTimeout(jh(a,b,c),25)}},dh=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},mh=function(a,b,c,d,e,f){var g=e;if(!g||"0"==g){if(a.l)return;a.l=!0;
g="0"}var h=a.wt;b&&(!h||h>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][g]=!0;if(f){if(b){var k=function(a){return Math.max(d,a)};fb(f,"mwt",k,0);c||fb(f,"nv.mwt",k,0)}!c&&e&&fb(f,"nv.ids",function(a){a.push(g);return a},[])}},fh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;for(var c=0;c<nh.length;c++)if(a.passingRules[c]){var d=oh[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=nh[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},ph=function(a,
b,c,d,e){var f,g,h=!1,k;switch(a){case "CLICK":k="cl";if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=hg(a);b&&eh("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":k="lcl";b&&!Yg&&(Yg=wa(P.location));mh(Zg,b||!1,c||!1,d,e,k);if(P.gtmHasLinkClickListenerTag)return;P.gtmHasLinkClickListenerTag=!0;f="click";g=hh(a,b||!1);break;case "FORM_SUBMIT":k="fsl";mh($g,b||!1,c||!1,d,e,k);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";
g=hh(a,b||!1);break;default:return}ya(k,"init")||(Q(P,f,g,h),fb(k,"legacyTeardown",function(a){return function(){T(a)&&a();oa(P,f,g,h)}},void 0))},ch=function(a){if(!Yg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=V(a);return Yg==wa(c)},lh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));
return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit};
var xa=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||sa(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};if(b&&bh)if("LINK_CLICK"==b)c["gtm.elementUrl"]=a.href;else if("FORM_SUBMIT"==b){var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d}c.hasOwnProperty("gtm.elementUrl")||(c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"");return c},qh=
function(a){mb.hasOwnProperty("autoEventsSettings")||(mb.autoEventsSettings={});var b=mb.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},rh=function(a,b,c){qh(a)[b]=c},fb=function(a,b,c,d){var e=qh(a),f=Ia(e,b,d);e[b]=c(f)},ya=function(a,b,c){var d=qh(a);return Ia(d,b,c)},sh=function(){var a=function(a){var b=Ta("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Zg=a("linkClickMap");
$g=a("formSubmitMap");};var th=/(^|\.)doubleclick\.net$/i,uh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Aa=function(a,b,c){for(var d=String(b||P.cookie).split(";"),e=[],f=0;f<d.length;f++){var g=d[f].split("="),h=ua(g[0]);if(h&&h==a){var k=ua(g.slice(1).join("="));k&&!1!==c&&(k=decodeURIComponent(k));e.push(k)}}return e},wh=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?vh():[d||"none"];for(var k=0;k<h.length;k++){var l=
g,m=h[k],n=c;if(th.test(z.location.hostname)||"/"==n&&uh.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=P.cookie;P.cookie=l;if(p!=P.cookie||0<=Of(Aa(a),b))return!0}return!1},xh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},yh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},vh=function(){var a=W(z.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var ea=function(a){var b=P;return zh?b.querySelectorAll(a):null},Ah=!1;if(P.querySelectorAll)try{var Bh=P.querySelectorAll(":root");Bh&&1==Bh.length&&Bh[0]==P.documentElement&&(Ah=!0)}catch(a){}var zh=Ah;var Ch=function(a){for(var b=[],c=P.cookie.split(";"),d=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push(f[1])}var g=[];if(!b||0==b.length)return g;for(var h=0;h<b.length;h++){var k=b[h].split(".");3==k.length&&"GCL"==k[0]&&k[1]&&g.push(k[2])}return g};var Dh=/^\w+$/,Eh=/^[\w-]+$/,Fh=/^\d+\.fls\.doubleclick\.net$/;function Gh(a){return a&&"string"==typeof a&&a.match(Dh)?a:"_gcl"}function Hh(a){if(a){if("string"==typeof a){var b=Gh(a);return{na:b,ka:b}}if(a&&"object"==typeof a)return{na:Gh(a.dc),ka:Gh(a.aw)}}return{na:"_gcl",ka:"_gcl"}}function Ih(a){var b=V(z.location.href),c=W(b,"host",!1);if(c&&c.match(Fh)){var d=W(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Jh(a){return a.filter(function(a){return Eh.test(a)})}var Lh=function(a){var b=Ih("gclaw");if(b)return b.split(".");var c=Hh(a);if("_gcl"==c.ka){var d=Kh();if(d&&(null==d.L||"aw.ds"==d.L))return[d.qa]}return Jh(Ch(c.ka+"_aw"))},Mh=function(a){var b=Ih("gcldc");if(b)return b.split(".");var c=Hh(a);if("_gcl"==c.na){var d=Kh();if(d&&("ds"==d.L||"aw.ds"==d.L))return[d.qa]}return Jh(Ch(c.na+"_dc"))};
function Kh(){var a=V(z.location.href),b=W(a,"query",!1,void 0,"gclid"),c=W(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=W(a,"fragment");b=b||rg(d,"gclid");c=c||rg(d,"gclsrc")}return void 0!==b&&b.match(Eh)?{qa:b,L:c}:null}
var Xa=function(a,b,c){var d=Hh(a);c=c||"auto";b=b||"/";var e=Kh();if(null!==e){var f=(new Date).getTime(),g=new Date(f+7776E6),h=["GCL",Math.round(f/1E3),e.qa].join(".");e.L&&"aw.ds"!=e.L||wh(d.ka+"_aw",h,b,c,g,!0);"aw.ds"!=e.L&&"ds"!=e.L||wh(d.na+"_dc",h,b,c,g,!0)}},Nh=function(){var a=Ih("gac");if(a)return decodeURIComponent(a);for(var b=[],c=P.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({zb:f[1],value:f[2]})}var g={};if(b&&b.length)for(var h=
0;h<b.length;h++){var k=b[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[b[h].zb]||(g[b[h].zb]=[]),g[b[h].zb].push({timestamp:k[1],qa:k[2]}))}var l=[],m;for(m in g)if(g.hasOwnProperty(m)){for(var n=[],p=g[m],t=0;t<p.length;t++)n.push(p[t].qa);n=Jh(n);n.length&&l.push(m+":"+n.join(","))}return l.join(";")};var Oh;a:{Oh="G"}var Ph={"":"n",UA:"u",AW:"a",DC:"d",GTM:Oh},ra=function(a){var b=Ca.f.split("-"),c=b[0].toUpperCase();return(Ph[c]||"i")+"1a"+(a&&"GTM"===c?b[1]:"")};var Th={},Uh,Vh;
var di=function(){};var li="www.googletagmanager.com/gtm.js";
var mi=li,ab=function(a,b,c,d){Q(a,b,c,d)},ba=function(a,b,c){u(a,b,c)},cb={},Oa=function(a,b,c){var d=cb[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.vb:a.bb,d=0;d<c.length;d++)z.setTimeout(c[d],0)}};d={status:1,vb:[],bb:[],bc:void 0};d.rd=u(a,e(d,2),e(d,3));cb[a]=d}0===d.status&&(d.bc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.vb.push(b),c&&d.bb.push(c))},ni=function(a,b){cb[a]={status:0,vb:[],bb:[],bc:b,rd:null}},ca=function(){return z.location.href},
bb=function(a){return W(V(a),"fragment")},U=function(a,b){return Z(a,b||2)},ma=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Lg(a)},aa=function(a,b){z[a]=b},q=function(a,b,c){var d=z;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},db=function(a,b,c){return ig(a,b,c)},x=function(a,b,c,d){var e=!d&&"http:"==z.location.protocol;e&&(e=2!==lb());return(e?b:a)+c},ia=function(a){var b=0;
return b},Cb=function(a){},ja=function(a){var b=!1;return b},eb=function(a,b){return Pf(a,b)},za=function(a){rh(a,"init",!0)},gb=function(a,b){fb(a,"nv.ids",b,[])};
var Eb=void 0,Ra=function(a){if(!Eb){var b=function(){var a=P.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<Eb.length;a++)w(Eb[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;ab(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Eb.length;a++)w(Eb[a])}))})}};Eb=[];P.body?b():w(b)}Eb.push(a)},lb=function(){var a=mi;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=P.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=
e[f].src;if(g){g=g.toLowerCase();if($f(g,c))return 3;1===d&&$f(g,b)&&(d=2)}}return d};var Bb=function(){return Ma()};var oi=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),pi={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},qi={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ri=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Og=function(a){var b=Z("gtm.whitelist");
var c=b&&ri(Qf(b),pi),d=Z("gtm.blacklist")||Z("tagTypeBlacklist")||[];oi.test(z.location&&z.location.hostname)&&(d=Qf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&ri(Qf(d),qi),f={};return function(g){var h=g&&g[Ya];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Of(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Of(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Of(e,h.a)))a:{for(var t=h.b||[],r=new Rf,v=0;v<e.length;v++)r.set(e[v],!0);for(v=0;v<t.length;v++)if(r.get(t[v])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _jsm=function(a){if(void 0!==a[Nd])try{var b=z.google_tag_manager;return b&&b.e&&b.e(a[Nd])}catch(c){}};_jsm.a="jsm";_jsm.b=["customScripts"];var si=void 0,ti="",ui=0,vi=void 0,_et=function(a){var b,c=Z("gtm.element"),d=Z("event"),e=Number(L());si===c&&ti===d&&ui>e-250?b=vi:(vi=b=c?ta(c):"",si=c,ti=d);ui=e;return b?b:a[Yc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(Z("gtm.elementUrl")||a[Yc]||""),c=V(b);return b};_eu.a="eu";_eu.b=["google"];var wi=function(a,b){this.h=a;this.s=b};wi.prototype.toString=function(){var a=""+this.h;1<this.s&&(a=a+"-"+this.s);return a};var xi=function(a,b){this.ub=a;this.Ka=b};xi.prototype.toString=function(){return""+this.Ka+"."+this.ub};var Ai=function(a,b){var c=new yi(null,a,b);zi(c);return c},yi=function(a,b,c){this.Ob=Math.floor(L().getTime()/864E5);this.Ia=b||"auto";this.ta=c||"/";var d=xh(this.Ia),e=yh(this.ta);this.N=a||new wi(d,e);this.m=[];this.I=new Rf},Ci=function(a,b,c){b&&(""==c.ub?Bi(a,b):(a.I.contains(b)||a.m.push(b),a.I.set(b,c)))},Di=function(a,b){for(var c=0;c<b.length;c++)Ci(a,b[c][0],b[c][1])},Bi=function(a,b){var c=Of(a.m,b);0<=c&&a.m.splice(c,1);a.I.set(b,void 0)},Ei=function(a){for(var b=[],c=0;c<a.m.length;c++){var d=
a.m[c];b.push([d,a.I.get(d)])}return b},Fi=function(a){for(var b=0,c=0;c<a.m.length;c++)b=Math.max(b,a.I.get(a.m[c]).Ka);return 864E5*b};yi.prototype.toString=function(){if(0==this.m.length)return"";for(var a=[],b=0;b<this.m.length;b++){var c=this.m[b];a.push(""+c+"."+this.I.get(c).toString())}return"GAX1."+this.N.toString()+"."+a.join("!")};
var Gi=function(a,b){for(var c=new Date,d=yh(a.ta),e=[],f=0;f<a.m.length;f++){var g=a.m[f];a.I.get(g).Ka<a.Ob&&e.push(g)}for(f=0;f<e.length;f++)Bi(a,e[f]);if(a.m.length>(b||10))return!1;c.setTime(Fi(a));if("auto"!=a.Ia)return wh("_gaexp",a.toString(),a.ta,a.Ia,c);for(var h=vh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.N=new wi(xh(h[k]),d),wh("_gaexp",a.toString(),a.ta,h[k],c)))return!0;return!1},zi=function(a){for(var b=a.N.h,c=a.N.s,d=Aa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Hi(a,d[f]);g&&e.push(g)}ag(e,
function(a,d){var e=a.N,f=d.N;return e.h==f.h&&e.s==f.s?!1:e.h==b&&e.s==c?!0:f.h==b&&f.s==c?!1:e.h==b?f.h!=b||e.s<f.s:f.h==b?!1:e.s==c?f.h!=b&&(f.s!=c||e.h<f.h):f.s==c?!1:e.h<f.h||e.h==f.h&&e.s<f.s});a.N=0<e.length?e[0].N:new wi(b,c);for(f=e.length-1;0<=f;f--)Di(a,Ei(e[f]))},Hi=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=ua(e[0]);if(0!=f.length){var g=2==e.length?ua(e[1]):"1";if(Nf(f)&&Nf(g)){d=new wi(X(f),X(g));
break a}}}d=void 0}if(d){for(var h=new yi(d,a.Ia,a.ta),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Nf(m[1]))return;Ci(h,m[0],new xi(m[2],X(m[1])))}}return h}}};var _v=function(a){var b=Z(a[fe].replace(/\\\./g,"."),a[Qc]);return void 0!==b?b:a[Yc]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(Z("gtm.referrer")||P.referrer);if(!b)return b;var c=V(b);return b};_f.a="f";_f.b=["google"];var Li=function(a){var b=z.location,c;(c=a[Nc]?a[Nc]:Z("gtm.url"))&&(b=V(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[yc]&&(f=W(b,a[yc],a[Se],a[Xc],a[Fe]));return f},_u=Li;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[$b]).indexOf(String(a[ac]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[$b])==String(a[ac])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[ac],a[Hd]?"i":void 0)).test(a[$b])};_re.a="re";_re.b=["google"];var hb=new String("undefined"),ub=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===hb?b:a[d]);return c.join("")}};ub.prototype.toString=function(){return this.resolve("undefined")};ub.prototype.valueOf=ub.prototype.toString;var Vi={},vb=function(a,b){var c=Xf();Vi[c]=[a,b];return c},Wi=function(a){var b=a?0:1;return function(a){var c=Vi[a];if(c&&T(c[b]))c[b]();Vi[a]=void 0}};var Xi=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Yi=function(a,b){return a<b?-1:a>b?1:0};var Zi;a:{var $i=Gb.navigator;if($i){var aj=$i.userAgent;if(aj){Zi=aj;break a}}Zi=""};var bj=function(a){bj[" "](a);return a};bj[" "]=function(){};var dj=function(a,b){var c=cj;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var ej=-1!=Zi.indexOf("Opera"),fj=-1!=Zi.indexOf("Trident")||-1!=Zi.indexOf("MSIE"),gj=-1!=Zi.indexOf("Edge"),hj=-1!=Zi.indexOf("Gecko")&&!(-1!=Zi.toLowerCase().indexOf("webkit")&&-1==Zi.indexOf("Edge"))&&!(-1!=Zi.indexOf("Trident")||-1!=Zi.indexOf("MSIE"))&&-1==Zi.indexOf("Edge"),ij=-1!=Zi.toLowerCase().indexOf("webkit")&&-1==Zi.indexOf("Edge"),jj;
a:{var kj="",lj=function(){var a=Zi;if(hj)return/rv:([^\);]+)(\)|;)/.exec(a);if(gj)return/Edge\/([\d\.]+)/.exec(a);if(fj)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ij)return/WebKit\/(\S+)/.exec(a);if(ej)return/(?:Version)[ \/]?(\S+)/.exec(a)}();lj&&(kj=lj?lj[1]:"");if(fj){var mj,nj=Gb.document;mj=nj?nj.documentMode:void 0;if(null!=mj&&mj>parseFloat(kj)){jj=String(mj);break a}}jj=kj}
var oj=jj,cj={},pj=function(a){return dj(a,function(){for(var b=0,c=Xi(String(oj)).split("."),d=Xi(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Yi(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Yi(0==k[2].length,0==l[2].length)||Yi(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})};var yb=function(a,b){var c="";fj&&!qj(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(rj)a.srcdoc=d;else if(sj){var e=a.contentWindow;if(e){var f=e.document;f.open("text/html","replace");f.write(d);f.close()}}else tj(a,d)},rj=ij&&"srcdoc"in document.createElement("IFRAME"),sj=hj||ij||fj&&pj(11)||gj,tj=function(a,b){fj&&pj(7)&&!pj(10)&&6>uj()&&vj(b)&&(b=wj(b));var c=
function(){var c=a.contentWindow;c&&(c.goog_content=b,c.location.replace("javascript:window.goog_content"))};fj&&!qj(a)?xj(a,c):c()},uj=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},qj=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{bj(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},yj=0,xj=function(a,b){var c="goog_rendering_callback"+yj++;Gb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},vj=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},wj=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Oj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=Lj(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=Mj(f,g);Nj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},Pj=null,Lj=function(a){if(Pj)return Pj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Pj=
c}0==a.styleSheets.length&&a.createStyleSheet();return Pj=a.styleSheets[0]},Mj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},Nj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Wj={},Xj=void 0,Yj=function(a){var b=Wj[a];b||(b={id:a,w:[],pa:0,Ab:null,ib:void 0,pb:!1},Wj[a]=b);Xj=b},ak=function(a,b,c,d){var e=Xj;if(!zh||!e)return!1;var f={id:e.id+":"+e.w.length,tc:b,ea:[],oc:c,O:a,Wa:0,Sa:d||null,Nb:0,oa:!1};e.w.push(f);null===a?(f.oa=!0,b(null)):Zj(e);return!0},bk=function(a){var b=Oj(a,"visibility","hidden",!0);return function(){T(b)&&b.apply();b=null}},ck=function(a,b,c,d){var e=b;if(!sb){var f=bk(a.F);tb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return ak(a,
e,c,d)},Zj=function(a){if(!a.pb){for(var b=a.pa;b<a.w.length;b++){var c=a.w[b],d=b==a.pa;if(!c.oa&&!dk(d,c))break;c.oa&&d&&a.pa++}a.w.length>a.pa?(a.Ab||(a.Ab=z.setTimeout(function(){a.Ab=null;Zj(a)},80)),sb||a.ib||(a.ib=function(){w(function(){Zj(a)})},Q(P,"DOMContentLoaded",a.ib))):ek(a)}},ek=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.O)for(var d=ea(c.O.F)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(fk(f,c.id),c.ea.push(hk(f,c.id)))}}},
dk=function(a,b){var c=[];if(b.O){var d=ik(b.O,b.id),e=null;b.Sa&&(e=ik(b.Sa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!sb&&(null===b.Sa.v||b.Nb+c.length<b.Sa.v)))break;c.push({element:g,ud:h})}}if(!sb&&b.oc&&(!a||null==b.O.v||b.O.v!=b.Wa+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].ud,n;b.Wa++;fk(l,b.id);m&&(b.Nb++,n=b.id+"-t",fk(m,n));var p=b.tc(l,m);T(p)&&b.ea.push(p);b.ea.push(hk(l,b.id));m&&n&&b.ea.push(hk(m,n))}if(b.O.v&&
b.O.v==b.Wa||sb)b.oa=!0;return!0},fk=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},hk=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},ik=function(a,b){for(var c=ea(a.F)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.M&&!jk(f))break;d.push(f)}}return d},jk=function(a){if(sb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var _cl=function(a,b){ph("CLICK");w(b)};_cl.a="cl";_cl.b=["google"];var Fk=function(a){if(!a)return!1;if(a[Zb]&&$a(a[ac])){for(var b=a[ac],c=0;c<b.length;c++)if(a[ac]=b[c],Sf(a))return!0;return!1}return Sf(a)};var al=76,bl=[],cl=[],Pg=[],dl=new Rf,el=[],fl=[],nh=[],oh=[],gl=function(){this.U=[]};gl.prototype.set=function(a,b){this.U.push([a,b]);return this};gl.prototype.resolve=function(a,b){for(var c={},d=0;d<this.U.length;d++){var e=Sg(this.U[d][0],a,b),f=Sg(this.U[d][1],a,b);c[e]=f}return c};var hl=function(a){this.index=a};hl.prototype.resolve=function(a,b){var c=Pg[this.index];if(c&&!b(c)){var d=c[Za];if(a){if(a.get(d))return;a.set(d,!0)}c=Sg(c,a,b);a&&a.set(d,!1);return Sf(c)}};
var _M=function(a){return new hl(a)},il=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Sg(bl[a[f]],b,c);g===hb&&(e=!0);d.push(g)}return e?new ub(d):d.join("")}},_T=function(a){return new il(arguments)},jl=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Sg(a[0],c,d);if(a[0]instanceof hl&&b(8)&&b(16)){if(e===hb)return e;var f=Ga();dl.set(f,e);return'google_tag_manager["'+Ca.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=Gk[a[g]](e);return e}},_E=function(a,b){return new jl(arguments)},kl=function(a,b){this.D=a;this.xa=b},_R=function(a,b){return new kl(a,b)};
var Sg=function(a,b,c){var d=a;if(a instanceof hl||a instanceof gl||a instanceof il||a instanceof jl)return a.resolve(b,c);if(!(a instanceof kl))if($a(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Sg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Sg(a[f],b,c))}return d},nl=function(){for(var a=[_jsm,'platform','(function(){var a\x3dnavigator.userAgent;a:{for(var c\x3d[{platform:\x22Frodo\x22,pattern:/com.douban.frodo/i},{platform:\x22WeChat\x22,pattern:/MicroMessenger/i},{platform:\x22Weibo\x22,pattern:/Weibo/i},{platform:\x22QQ\x22,pattern:/ QQ/i}],b\x3d0,d\x3dc.length;b\x3cd;b++)if(c[b].pattern.test(a)){a\x3dc[b].platform;break a}a\x3d\x22Others\x22}return a})();',_T(2),'open-source','(function(){var a\x3dwindow.location.search;a:{for(var c\x3d[{source:\x22\\u670b\\u53cb\\u5708\x22,pattern:/timeline/i},{source:\x22\\u7fa4\\u804a\x22,pattern:/groupmessage/i},{source:\x22\\u79c1\\u804a\x22,pattern:/singlemessage/i}],b\x3d0,d\x3dc.length;b\x3cd;b++)if(c[b].pattern.test(a)){a\x3dc[b].source;break a}a\x3d\x22Others\x22}return a})();',_T(5),'share-source','(function(){var a\x3dwindow.location.search;a:{for(var c\x3d[{source:\x22\\u516c\\u4f17\\u53f7\x22,pattern:/weixin-feed/i},{source:\x22frodo\x22,pattern:/FeatureFeedTheme|dt_/i}],b\x3d0,d\x3dc.length;b\x3cd;b++)if(c[b].pattern.test(a)){a\x3dc[b].source;break a}a\x3d\x22Others\x22}return a})();',_T(8),_eq,__e,'_event','1',_M(3),'gtm.js','2413993_2147479553',__ua,true,false,'TRACK_PAGEVIEW','index','dimension',_M(0),{21:13,22:23},[24],'UA-53594431-4',4,'3',_M(1),{21:28,22:29},[30],9,_cn,_v,'Click Classes','gtm.elementClasses',_M(4),'promo_button download_app','gtm.click','点击','2413993_34','下载','TRACK_EVENT',11,_re,_u,'Page URL',_M(5),'/page','2413993_46','fieldName','value','sampleRate','4',{51:53,52:54},[55],'UA-53594431-3',12,'UA-53594431-6',13,14,'2413993_47',_cl,15,'Page Hostname','host','Page Path','path',_f,'Referrer','Event','Click Element','gtm.element','Click ID','gtm.elementId','Click Target','gtm.elementTarget','Click URL','gtm.elementUrl',_et,'Click Text'],b=[],c=0;c<a.length;c++)b[c]=
ml(c,a);return b},ml=function(a,b){var c=b[a],d=c;if(c instanceof hl||c instanceof jl||c instanceof il||c instanceof kl)d=c;else if($a(c)){d=[];for(var e=0;e<c.length;e++)d[e]=ml(c[e],b)}else if("object"==typeof c){d=new gl;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],ml(c[f],b))}return d},pl=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
bl[e[1]]);if(1==a){var f=ol(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=cl[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=ol(e[g]);3==a&&(c[d]=bl[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=bl[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},ol=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<al;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},ql=function(a,b,c){a.push.apply(a,pl(b,c))};var rl;
var Rg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=ul[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},xl=function(a){},yl=function(a,b){},Ug=function(a){};var zl,Al;var Ll=function(a){return function(){}},Ml=function(a){return function(){}};var Nl=function(a){var b=this;this.i=a;this.la=this.fc=!1;this.Ra=[];this.La=[];this.C=function(){b.la||Wf(b.Ra);Zf(b,1);if(Ob[a])for(var c=0;c<Ob[a].length;c++)Ob[a].shift().C()};this.B=function(){b.la||Wf(b.La);Zf(b,2);if(Ob[a])for(var c=0;c<Ob[a].length;c++)Ob[a].shift().B()};this.H=wb},Ol=function(a,b){a.Ra.push(b)},Pl=function(a,b){a.La.push(b)},Ql=function(a){this.P=[];this.wb=[];this.Qb={};this.Wb=[];this.ba=0;this.tb={};this.yb={};this.xb={};this.event=a};Ql.prototype.addListener=function(a){this.Wb.push(a)};
var Rl=function(a){0<a.ba||Wf(a.Wb)},Sl=function(a,b,c,d,e,f){if(!c.la){a.P[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=$a(d)?d.slice():["or",d];e=$a(e)?e.slice():[e];f=$a(f)?f.slice():[f];a.Qb[b]=d;a.tb[b]=0<e.length;a.yb[b]=0<f.length;a.ba++;var g=function(){0<a.ba&&!a.tb[b]&&!a.yb[b]&&a.ba--;Rl(a)};Ol(c,g);Pl(c,g)}},Xl=function(a){for(var b=[],c={},d=0;d<a.P.length;c={W:c.W},d++)if(c.W=a.P[d],c.W){var e=a.Qb[d],f=a.tb[d],g=a.yb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=
Tl(e,c.W.H),k=0;k<e.length;k++)e[k]instanceof kl&&e[k].D!=d&&Ul(a,e[k].D,h);(f||g)&&Vl(a,d,function(a){return function(){0<a.W.G.ba&&a.W.G.ba--;Rl(a.W.G)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.P[b[d]].H();for(d=0;d<a.wb.length;d++){var l=a.wb[d];Wl(l);0<l.length&&l[0].H()}},Ul=function(a,b,c){a.P[b]&&(Ol(a.P[b],function(){c(b,!0)}),Pl(a.P[b],function(){c(b,!1)}))},Tl=function(a,b){var c=wb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof kl&&a[h].D===e||a[h]===
e){g=h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Vl=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=fl[b];if(a.event.g(h)){}else g=Yl(h,b,a.event.g,a);if(c=g){var k=Zl(b,!0);0<k.length&&f(k[0].D);d.push(c);var l=Zl(b,!1);0<l.length&&
f(l[0].D)}else e=!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Zl(h.i,!0);if(0<k.length){var l=d[g-1],m=$l(h);Ol(l,m);0==k[0].xa?Pl(l,m):Pl(l,c)}var n=Zl(h.i,!1);0<n.length&&(m=$l(d[g+1]),Ol(h,m),0==n[0].xa?Pl(h,m):Pl(h,c))}Ol(d[d.length-1],c);Pl(d[d.length-1],c);a.wb.push(d)}},Zl=function(a,b){var c=b?Pe:ff,d=fl[a],e=void 0===d[c]?[]:d[c];return $a(e)?e:[e]},$l=function(a){return function(){a.H()}},Wl=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Nb[e],g=f.firingOption;
if(0!=g&&(1==g&&void 0!==d.G.xb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Zl(a[c+1].i,!0);if(0<h.length&&1==h[0].xa)for(++c;c<a.length;c++)b.push(a[c])}}var k=am(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],t=p[0],r=p[p.length-1],v,y=0;y<a.length;y++){var H=a[y];!m&&H.i==t&&0<y&&(m=a[y-1]);H.i==r&&y<a.length-1&&(n=a[y+1]);if(-1<Of(p,H.i))if(v=a.splice(y,1)[0],H.i==r)break;else y--}if(v){var G=Number(l),D=m,K=n;if(D){var C=D.Ra[0],E=D.La[0],
A=D;A.Ra=[];A.La=[];Ol(D,C);Pl(D,E)}if(D&&K){var B=$l(K);Ol(D,B);var I=Zl(D.i,!1);0<I.length&&I[0].D!=G&&0==I[0].xa&&Pl(D,B);var J=Zl(K.i,!0);0<J.length&&J[0].D!=G&&0==J[0].xa&&Pl(D,B)}}}},am=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Zl(a,!0);0<b.length&&f(b[0].D);e.push(a);var c=Zl(a,!1);0<c.length&&f(c[0].D)};f(d.i);b[d.i]=e}bm(a,b);return b},bm=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Of(b[e],d)){delete b[d];
break}}};var cm=function(a,b,c){return function(){a[Bd]=b.C;a[Cd]=b.B;var d=b.i,e=b.G&&b.G.xb[d],f=Nb[d]&&Nb[d].state,g=e?void 0!==e:b.fc||b.la,h=Nb[d]&&Nb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Zf(b,0);var m=b.G?b.G.event:void 0,n=a;n=Sg(n,new Rf,c);a=n;if(m){}Sf(a,b.C,b.B)}else k&&0==f||l&&0==e?Ob[d].push(b):k&&1==f||l&&1==e?b.C():b.B()}},Yl=function(a,b,c,d){function e(a){return a.i===b}var f=function(){var a=d&&d.P;return a&&Pf(a,e)}()||new Nl(b);f.G=d;Ol(f,Ll(a));Pl(f,Ml(a));f.H=cm(a,f,c);return f};var jm=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=el[b]&&Sg(el[b],new Rf,c),e=d;d&&(e=Fk(d));a[b]=[e,d]}return a[b]}},km=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.aa(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.aa(e[d],a.g)[0])return!1;return!0},lm=!1;
Ig=function(a,b,c,d,e){switch(b){case "gtm.js":if(lm)return!1;lm=!0;break;case "gtm.sync":if(Z("gtm.snippet")!=Kb)return!1}for(var f={id:a,name:b,Fa:d||wb,ja:ol(),Pa:ol(),aa:jm(),g:Og(c)},g=[],h=0;h<nh.length;h++)if(km(f,nh[h])){g[h]=!0;for(var k=f,l=nh[h],m=l[1],n=0;n<m.length;n++)k.ja[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Pa[p[n]]=!0}else g[h]=!1;var R=[];for(var M=0;M<al;M++)if(f.ja[M]&&!f.Pa[M])if(f.g(fl[M])){}else{R[M]=
fl[M];}f.ua=R;for(var na=new Ql(f),fa=0;fa<al;fa++)if(f.ja[fa]&&!f.Pa[fa])if(f.g(fl[fa])){}else{var La=f.ua[fa],gk=Yl(La,fa,f.g,na);Sl(na,fa,gk,La[Zc],La[Pe],La[ff]);if(La[Pb])break}na.addListener(f.Fa);Xl(na);Rl(na);e&&T(e)&&e({passingRules:g,resolvedTags:f.ua});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var jg in f.ua)if(f.ua.hasOwnProperty(jg)){var kg=f.ua[jg];if(void 0==kg[Za]||!$f(kg[Za],"_implicit"))return!0}return!1};var nm=function(){};var om={};var tm=function(){};var mm={macro:function(a){if(dl.contains(a))return dl.get(a)}};mm.dataLayer=wg;mm.onHtmlSuccess=Wi(!0);mm.onHtmlFailure=Wi(!1);mm.callback=function(a){Va.hasOwnProperty(a)&&T(Va[a])&&Va[a]();delete Va[a]};
mm.Bc=function(){var a=z.google_tag_manager;a||(a=z.google_tag_manager={});mb=a;if(a[Ca.f]){var b=mb.zones;b&&b.registerNatural(Ca.f)}else{a[Ca.f]=mm;di();sh();bl.push.apply(bl,nl());ql(cl,0,"3:0,4:1,5:3,4:4,5:6,4:7,5:9,3:10,3:11,4:12,10:13,0:14,1:15,3:17,8:18,13:19,24:19,28:19,29:19,25:20,11:19,16:19,12:25,14:19,27:26,17:19,18:19,15:18,9:27,12:31,9:32,3:33,3:34,4:35,6:36,0:37,1:38,1:39,7:18,22:19,20:42,25:43,19:40,26:18,9:44,3:45,3:46,4:47,0:48,1:49,21:56,27:57,9:58,23:18,27:59,9:60,9:61,3:63,9:64,4:65,2:66,4:67,2:68,3:69,4:70,4:71,4:72,6:73,4:74,6:75,4:76,6:77,4:78,6:79,3:80,4:81");ql(Pg,1,"H,Z,hB,Ac,AAAAAc,AAAAAAAw,AAAAAAAQAgB,AAAAAAAQAAG,AAAAAAAAAAY,AUAAAAAAAAg,AAAAAEAAAAAD,AAAAAEAAAAAM,AAAAAEAAAAAw,AAAAAEAAAAAAD,AAAAAAAAAAAAM");ql(el,1,"AiB,AAAAAiB,AiAAAAC,AAAAAAAID");ql(fl,1,"AQ-_f,AQ-vvB,AQ6oPA8H,AQ-vOAAAc,AQ6vOAEAkD,AQ-_OAAAAF,AAAAAAAAAY");ql(nh,2,"B:jB::,G:E::,J:Y::");ql(oh,4,"16.16.16.62:,41:,50.50:");for(var c=0;c<fl.length;c++){var d=fl[c],e=1;d[me]?e=2:
d[yf]&&(e=0);Nb[c]={firingOption:e,state:void 0};Ob[c]=[]}Eg();Xg();var n=z;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)eg();else{Q(P,"DOMContentLoaded",eg);Q(P,"readystatechange",eg);if(P.createEventObject&&P.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(H){}p&&gg()}Q(n,"load",eg)}"complete"===P.readyState?pg():Q(z,"load",pg);tm();nm();a:{}}};mm.Bc();var _vs="res_ts:1500869045141000,srv_cl:181480358,ds:live,cv:36";
})()
